# Configuración general del proyecto
project:
  name: "Kaspersky Security Tools"
  version: "1.0.0"
  description: "Herramientas de seguridad y análisis forense"
  author: "Hector Flores"
  license: "MIT"

# Configuración de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "data/logs/app.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Configuración de análisis
analysis:
  timeout: 300  # segundos
  max_file_size: 104857600  # 100MB
  temp_dir: "data/temp"
  rules_dir: "data/rules"

# Configuración de red
network:
  scan_timeout: 5  # segundos
  max_threads: 10
  ports:
    common: [21, 22, 23, 25, 53, 80, 110, 143, 443, 445, 3389]
    range: "1-1024"

# Configuración de seguridad
security:
  hash_algorithms: ["md5", "sha1", "sha256"]
  max_password_length: 32
  min_password_length: 8
  password_complexity: true

# Configuración de monitoreo
monitoring:
  interval: 60  # segundos
  alert_threshold: 3
  max_alerts: 100

# Configuración de reportes
reports:
  format: "json"
  output_dir: "data/reports"
  max_history: 30  # días 